### ISSUE TITLE
Tap 2 (or more) always starts hidden

### ISSUE THREAD

**Issue by dboyd13** [johnnyruz/kegbot-android#3]
When configured with more than one tap, the other tap always start as hidden on the Kegbot App. Whenever the tablet is restarted or kegbot-android crashes (rarely), the additional taps have to manually be made visible again.

https://github.com/Kegbot/kegbot-android/issues/99

Had a quick look through the code, it appears that the 'ON/OFF' toggle for each tap is not saved into preferences currently. Is this something you'd be willing to add to the KegBot android app in your fork?

**Comment by johnnyruz** [comment]
Hi @dboyd13,

I believe I have this resolved and have created an APK available [HERE](https://drive.google.com/open?id=1n6v8xU-C7F5-jtk6Anoyttlu8X9GklIv) that resolves this issue. It also has several other minor fixes/additions in it.

Give it a try and let me know if you have any issues. I'll be adding all of these changes as PRs into the main Kegbot project as well.

**Comment by dboyd13** [comment]
Thanks very much! I will try this out and report back. Which other minor issues does this resolve? Wasn’t able to see any associated commit to look over the code changes.

**Comment by johnnyruz** [comment]
I had a little misunderstanding about your issue initially. With multiple taps, when the app starts up the home screen always starts up with the second-to-last tap and the activity history displayed. I thought that's what your issue referenced so I added code to start the app with the first tap displayed.

Once I realized you were talking about a separate issue I resolved that, but kept my other "fix" in there. 

All of my changes are being made in a "johnnyruz" branch, so you should see all of my commits there.

**Comment by dboyd13** [comment]
Excellent! Thanks very much. A quick test I did earlier shows it’s working as expected now

**Comment by johnnyruz** [comment]
Resolved with commit 
3ef28f4 in johnnyruz branch.
